#!/bin/bash
set -x
SOURCES=(main.c braille_buffer.c chart.c)
FLAGS='-Wall -Werror -Wshadow -Wextra -Wno-unused-parameter -std=gnu11 -ggdb3'
EXE='termpix'
LINK='-lncursesw -lm'
clang $FLAGS ${SOURCES[*]} -o $EXE $LINK
